import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import SideWithNav from "src/components/SideWithNav";
import IntlProvider from "src/utils/IntlProvider";
import "../globals.css";
import { Providers } from "../providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ar" }];
}

const getDirection = (lang) => (lang === "ar" ? "rtl" : "ltr");

export default async function RootLayout({ children, params }) {
  const lang = params.lang || "en";

  let messages;
  try {
    messages = (await import(`../../public/locales/${lang}/common.json`))
      .default;
  } catch (error) {
    console.log("error", error);
    notFound();
  }

  const dir = getDirection(lang);

  return (
    <html lang={lang} dir={dir}>
      <body className={inter.className}>
        <Providers>
          <ThemeProvider attribute="class">
            <IntlProvider locale={lang} messages={messages}>
              <SideWithNav />
              {children}
              <ToastContainer />
            </IntlProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
