import { Inter } from "next/font/google";
import "../globals.css";
import Header from "src/components/Header";
import { ThemeProvider } from "next-themes";
import { LanguageProvider } from "src/contexts/LanguageContext";
import { notFound } from "next/navigation";
import IntlProvider from "src/utils/IntlProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ar" }];
}

export default async function RootLayout({ children, params }) {

  console.log("params:::::::::", params)
  const lang = params.lang || 'en';
  console.log("lang:::::::::", lang)

  let messages;
  try {
    messages = (await import(`../../public/locales/${lang}/common.json`))
      .default;
  } catch (error) {
    console.log("error::::::::", error)
    notFound();
  }

  return (
    <html lang={lang}>
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <LanguageProvider>
            <IntlProvider locale={lang} messages={messages}>
              <Header />
              {children}
            </IntlProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
