import { Inter } from "next/font/google";
import "./globals.css";
import Header from "src/components/Header";
import { ThemeProvider } from "src/contexts/theamProvider";
import { LanguageProvider } from "src/contexts/LanguageContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <LanguageProvider>
            <Header />
            {children}
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
